### ISSUE TITLE
questions about ff-gpu

### ISSUE THREAD

**Issue by zjin-lcf** [itzmeanjan/ff-gpu#18]
There are some questions after browsing your programs.

In rescue_prime.cpp:

sycl::long4 ovr_0 = tmp_3 > std::numeric_limits<uint64_t>::max() - tmp_4;

I am not familiar with the math, is it  tmp_3 > ( std::numeric_limits<uint64_t>::max() - tmp_4 ) ?

In addition, how do you verify the results of the Merkel construction on a GPU ?

Thanks

**Comment by itzmeanjan** [comment]
HI,

I think you're referring to https://github.com/itzmeanjan/ff-gpu/blob/89c9719e5897e57e92a3989d7d8c4e120b3aa311/rescue_prime.cpp#L20

Above linked line checks whether previous vector addition https://github.com/itzmeanjan/ff-gpu/blob/89c9719e5897e57e92a3989d7d8c4e120b3aa311/rescue_prime.cpp#L19 caused any kind of overflow or not.

**Comment by itzmeanjan** [comment]
Speaking of Merkle Tree implementation correctness check, it's pretty trivially done at this moment. If you see this [file](https://github.com/itzmeanjan/ff-gpu/blob/89c9719e5897e57e92a3989d7d8c4e120b3aa311/tests/test_merkle_tree.cpp), I assert equality of root ( 32 -bytes ) of Merkle Trees, computed using various implemented approaches; see https://github.com/itzmeanjan/ff-gpu/blob/89c9719e5897e57e92a3989d7d8c4e120b3aa311/tests/test_merkle_tree.cpp#L86-L96

**Comment by zjin-lcf** [comment]
Yes.  Is parenthesis needed ?

Could the following two lines be reduced to a single line shown below ? I tried, but found that the compiler reports errors for the single-line version. 

sycl::long4 und_0 = ab < d; // check if underflowed
sycl::ulong4 tmp_1 = und_0.convert<ulong>();

to 

sycl::ulong4 und_0 = ab < d ? 

Thanks.

**Comment by itzmeanjan** [comment]
> Yes. Is parenthesis needed ?

I don't think so, given C++ https://en.cppreference.com/w/cpp/language/operator_precedence, but can be added for sake of better clarity.

> Could the following two lines be reduced to a single line shown below ? I tried, but found that the compiler reports errors for the single-line version.
> 
> sycl::long4 und_0 = ab < d; // check if underflowed sycl::ulong4 tmp_1 = und_0.convert();
> 
> to
> 
> sycl::ulong4 und_0 = ab < d ?

I don't think so, as `long4` will be return type when `<` operator is applied with two SYCL vector operands, see table 140 in SYCL specification https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:vector.type

After that it needs to be explicitly converted to unsigned vector `ulong4`.

**Comment by zjin-lcf** [comment]
Thank you again for your answers!
